apiVersion: v1
kind: Service
metadata:
  name: osticket-mysql
  labels:
    app: osticket-mysql
spec:
  ports:
    - port: 3306
  selector:
    app: osticket-mysql
    tier: mysql
  clusterIP: None
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: osticket-mysql
  labels:
    app: osticket-mysql
spec:
  selector:
    matchLabels:
      app: osticket-mysql
      tier: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: osticket-mysql
        tier: mysql
    spec:
      containers:
      - image: mysql:5.6
        name: mysql
        volumeMounts:
        - mountPath: /var/lib/mysql
          name: db-volume
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: secret
        - name: MYSQL_USER
          value: osticket
        - name: MYSQL_PASSWORD
          value: secret
        - name: MYSQL_DATABASE
          value: osticket
        ports:
        - containerPort: 3306
          name: mysql
      volumes:
        - name: db-volume
          hostPath:
            path: /mysqldata
            type: Directory
        
