apiVersion: v1
kind: Secret
metadata:
  name: osticket-secrets
  labels:
    app: osticket
type: Opaque
data:
  SMTP_HOST: bWFpbC5nbXgubmV0
  SMTP_PORT: MjU=
  SMTP_FROM: b3N0aWNrZXRAdGJ6LmNo
  SMTP_USER: bWFhcy10ZXN0QGdteC5jaA==
  SMTP_PASSWORD: JjhyaCgqSTZES3Uh
